### ISSUE TITLE
Setting drawer__inner__mastodon as fixed causes issues with scrolling left and right on small screens

### ISSUE THREAD

**Issue by UmbyUmbreon** [trwnh/mastodon-flat-css#1]
Tested on Firefox and Chrome with the same results. This happens no matter where you start scrolling.

![Example](https://thumbs.gfycat.com/DistantJauntyDungenesscrab-size_restricted.gif)

This also causes issues with the Compose box with extremely long toots. It's not possible to click the TOOT! button if it's obscured by our elephant friend.

**Comment by trwnh** [comment]
Good catch! I hadn't tested at different screen sizes quite yet. This should no longer be an issue! I've pushed the fix to both GitHub and userstyles.org now.

**Comment by UmbyUmbreon** [comment]
Yep, looks like that does the trick!
