### ISSUE TITLE
Is it possible to instatt your css style directly in an instance?

### ISSUE THREAD

**Issue by privacytoolsIO** [trwnh/mastodon-flat-css#9]
I would like to use it on https://social.privacytools.io/ without having users download a browser addon. Thanks for your help, buddy.

**Comment by trwnh** [comment]
Please see https://github.com/trwnh/mastomods for the instance theme version. Right now this repo is purely for the userstyle that gets uploaded to userstyles.org -- although the readme doesn't reflect this yet.
